### ISSUE TITLE
GWP Using BHoM

### ISSUE THREAD

**Issue by jared-gonz20** [BHoM/documentation#53]
Hello, I am currently using BHoM for a project that I am currently working on. I wanted to use the BHoM code so I can see the embodied carbon produced by certain elements in my Revit model. However, when I use an explode node to track the global warming potential of specific data sets it does not show up. I was wondering if BHoM still has the option to track GWP, and if so where can I find it. If not, then what other options in BHoM can I use to track global warming potential. 
![GitHub ](https://user-images.githubusercontent.com/117859957/200926186-0cafd294-cf4c-40ea-a57f-9cf9ea558ed1.png)

**Comment by michaelhoehn** [comment]
Hey @jared-gonz20 thanks for the question! 

Yes, we most certainly track GWP, but the object model is actually set up to be able to track many more environmental metrics. Here's an example where I've constructed my own EPD object using the LCA object model (oM): 

![image](https://user-images.githubusercontent.com/54593392/200944679-ccd8d73e-0e85-462b-b944-f59c87c3f9fb.png)

You'll note that there are a few inputs required in order to construct a functional EPD. Those properties are what you're showing via the explode method. Now if you were to explode the `EnvironmentalMetric` you would see the exact same setup from my example above. The metric's quantity and type are stored here. This means that you could measure all sorts of environmental metrics, and could even have multiple metrics and values within an EPD as well. 

Since you're using one of our pre-baked sample datasets from EC3 you should be seeing only GWP metrics being used. So you should be able to simply plug the dataset into the `GetEvaluationValue` method and receive the single value if that's what you're mainly after. Hope this helps!

**Comment by jared-gonz20** [comment]
Thank you for this solution I implemented it into my Dynamo project. However, I did run into another problem with another method that I am trying. The return I get from the add fragment is null for all the items I have on my list. I am not sure how to fix this. It will be greatly appreciated, thank you.
![Null Return](https://user-images.githubusercontent.com/117859957/202301580-d1f053af-f69d-479e-8448-a2ca980f9d75.png)

**Comment by michaelhoehn** [comment]
Hey @jared-gonz20 sorry I think there's some general confusion about the use of addFragment possibly due to some outdated documentation in the toolkit. I'll make a note to check and update that to help moving forward. In the meantime, please check the following image of a script that adds an EPD to a physical object `Column`. Note the use of `SetProperty` here as opposed to `AddFragment`. This is actually modifying the material property data attributes on the object as opposed to nesting some data within a data fragment. The EPD objects are by namespace `MaterialFragments`, but do not function in the way you've noticed and will produce null outputs. 

I also noticed that you're trying to evaluate different types of physical objects, which is perfectly fine to do, but just note that due to the inconsistent nature of some physical objects and their properties, you may need to `SetProperty` using different `propName` input strings. A BHoM Door object for example has a `Construction` input, which would require the `propName` input to be `Construction.Layers.Material`. This is something we are actively working on to improve the UX by performing this mapping exercise automatically, but until that's resolved you'll need to use the `FilterByType` method and partition or various objects prior to setting their EPDs. 

Please let me know if this helps or if you're having any other issues!

![Physical Element Add EPD](https://user-images.githubusercontent.com/54593392/202516325-a98a4b43-6a14-404c-ad3d-873977c63e84.png)

**Comment by michaelhoehn** [comment]
I just check the Wiki and saw that it was updated already to reflect these changes, so likely the demo video you saw was just out of date. Please refer to this page for more information! 

https://github.com/BHoM/LifeCycleAssessment_Toolkit/wiki/Mapping-EPDs-to-Objects 

Let me know if this answers your questions!

**Comment by vietle-bh** [comment]
Documentation already updated by @michaelhoehn
