### ISSUE TITLE
Setting up adaptor project missing references

### ISSUE THREAD

**Issue by didimitrie** [BHoM/documentation#6]
Followed [this guide](https://github.com/BHoM/documentation/wiki/BH.Adapter-%E2%80%90-Linking-to-Commercial-Software#a-creating-a-new-software-toolkit-with-the-template) and the solution is not building due to missing references - 
[screenshot](https://user-images.githubusercontent.com/7696515/53092687-51849080-350d-11e9-81e9-936994bbd077.png). 

I guess there is a step in between that I'm missing :) 

I've also tried resolving this the missing references by removing and adding the specific projects by themselves, individually, but it feels like i'm running around headless as there's quite a few cross-dependencies and projects to add. How do you guys handle this?

**Comment by al-fisher** [comment]
🤦‍♂️ oh dear - @IsakNaslundBh this FYI this template is quite out of date now!

Sorry @didimitrie - thanks for uncovering! And sharing 😃 

You need to replace the references with new BHoM .dlls (a change was made to break the BHoM.dll into multiple .dlls matching the namespaces - to further facilitate extendability)

![image](https://user-images.githubusercontent.com/15924573/53096689-9f05fb00-3517-11e9-9a3e-e1be3e4abc44.png)

There are also some changes to the `BH.oM.Structure` namespace 
Change: using `BH.oM.Structural` to `BH.oM.Structure` for instance 
and also  `BH.oM.Structure.Properties.Section` is a change in namespace since this template was made 6 months ago! 
Sorry for all that!

This template was actually made to facilitate creation of Structural_Toolkits - so a lot of the content will be irrelevant for your needs anyway.

So should prop just delete the Structures specific code.
And then worth you looking at https://github.com/BHoM/Mongo_Toolkit 

@IsakNaslundBh @adecler FYI

**Comment by didimitrie** [comment]
Okay gotcha. Last one then regarding the source of these dlls: in speckle, we use submodules to pull in dependent projects in the solution, and then add references across the solution projects. 

Is this the preferred way in BHoM too, or should i just reference the dlls from, for example, their installation location, or wherever they're built at? Just trying to find the workflow you're using and i'll follow that for now.

**Comment by al-fisher** [comment]
We are directly referencing the built .dlls in the Output path which is being set to `..\Build\` for each project so common for each solution.

**Comment by IsakNaslundBh** [comment]
Working my way through updating the template now.

Will still be structures focused to some extent, but should work ok for other situations as well! Just need to delete some files!

Will aim to have something up today!

**Comment by al-fisher** [comment]
Thanks @IsakNaslundBh
